/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
package Parser;

public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTPRAGRAM = 1;
  public int JJTFUNTION = 2;
  public int JJTBLOCK = 3;
  public int JJTSTATE = 4;
  public int JJTSEQSTATEMENT = 5;
  public int JJTASSISTATE = 6;
  public int JJTDECLSTATE = 7;
  public int JJTSELSTATEMENT = 8;
  public int JJTSWITCHH = 9;
  public int JJTIFSTATE = 10;
  public int JJTBOOLEXPRESS = 11;
  public int JJTORFUNC = 12;
  public int JJTANDFUNC = 13;
  public int JJTNOTFUNC = 14;
  public int JJTBOOLEAN = 15;
  public int JJTLOOPSTATEMENT = 16;
  public int JJTFORLOOP = 17;
  public int JJTDOLOOP = 18;
  public int JJTLOOPSTATE = 19;
  public int JJTEXPRESS = 20;
  public int JJTADDITIVEEXPRESSION = 21;
  public int JJTMULTIPLICATIVEEXPRESSION = 22;
  public int JJTUNARYEXPRESSION = 23;
  public int JJTPANDUAN = 24;
  public int JJTISID = 25;
  public int JJTARRAY = 26;
  public int JJTSELFCHANG = 27;
  public int JJTAFTERCHANG = 28;
  public int JJTCALLFUNC = 29;
  public int JJTRELATION = 30;
  public int JJTTYPE = 31;
  public int JJTIDENTIFIER = 32;
  public int JJTIDENTIFIER1 = 33;
  public int JJTJUMPS = 34;
  public int JJTRETURNS = 35;
  public int JJTBREAKS = 36;
  public int JJTCONTINUES = 37;
  public int JJTINTEGER = 38;


  public String[] jjtNodeName = {
    "Start",
    "pragram",
    "Funtion",
    "Block",
    "State",
    "seqStatement",
    "assiState",
    "declState",
    "selStatement",
    "Switchh",
    "IFState",
    "BoolExpress",
    "orFunc",
    "andFunc",
    "notFunc",
    "Boolean",
    "loopStatement",
    "forLoop",
    "doLoop",
    "loopState",
    "Express",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PanDuan",
    "ISID",
    "array",
    "selfChang",
    "afterChang",
    "callFunc",
    "Relation",
    "type",
    "Identifier",
    "Identifier1",
    "jumpS",
    "ReturnS",
    "BreakS",
    "ContinueS",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=ef85ba74198b4d321a9c4f878baa8358 (do not edit this line) */
